In [34]:
import numpy as np
import  tensorflow as tf

In [35]:
#name scope for variables
with tf.name_scope("variables"):
#creating matrixes with 2x3 and 3x2 dimensions
    matrix1 = tf.Variable(tf.random_normal((2, 3)))
    matrix2 = tf.Variable(tf.random_normal((3, 2)))

#name scope for calculations
with tf.name_scope("calculations"):
#storing matrixs multiplication in result tensor
    matrixResult = tf.matmul(matrix1, matrix2)

#running new session and processing calculations
with tf.Session() as sess:
#variables initialization
    sess.run(tf.global_variables_initializer())
    print("matrix1 dim: ", matrix1.shape[0], matrix1.shape[1])
    print(sess.run(matrix1))
    print("matrix2 dim: ", matrix2.shape[0], matrix2.shape[1])
    print(sess.run(matrix2))
    print("matrixResult dim: ", matrixResult.shape[0], matrixResult.shape[1])
    print(sess.run(matrixResult))

matrix1 dim:  2 3
[[ 3.2066827e+00 -2.7988672e-01  1.3866361e+00]
 [ 1.5692974e-03  1.0802776e+00  2.2618444e+00]]
matrix2 dim:  3 2
[[-1.6349607  -0.80405706]
 [ 1.1311133   0.06899829]
 [ 2.3787012  -0.44767046]]
matrixResult dim:  2 2
[[-2.2609909  -3.2184234 ]
 [ 6.5996027  -0.93928546]]


In [36]:
#declaring two numpy arrays
a = np.random.rand(2,3)
b = np.random.rand(3,2)

#name scope for variables
with tf.name_scope("variables"):
#creating placeholders for x and y arrays
    x = tf.placeholder("float", [2, 3])            #no data here, it's just placeholder 
    y = tf.placeholder("float", [3, 2])            #no data here, it's just placeholder 

#name scope for calculations
with tf.name_scope("calculations"):
#creating tensor z for multiplication of x and y matrixes
    z = tf.matmul(x,y)

#running new session and processing calculations
with tf.Session() as session:
#feeding placeholder with numpy arrays and calculating result of multiplication
    result = session.run(z, feed_dict={x: a, y:b})
    print("x dim: ", x.shape[0], x.shape[1])
    print("y dim: ", y.shape[0], y.shape[1])
    print("z dim: ", z.shape[0], z.shape[1])
    print("z matrix:")
    print(result)

x dim:  2 3
y dim:  3 2
z dim:  2 2
z matrix:
[[0.8607227  0.71639705]
 [0.8744667  0.857868  ]]


In [37]:
# Creating x and y numpy arrays

x_np = np.random.rand(50, 1)
y_np = np.reshape(5 * x_np  + 2, (-1))

In [38]:
# Number of nodes in hidden layers
hidden_nodes = 50

#name scope for variables
with tf.name_scope("inputs_variables"):
#creating placeholders for x and y arrayes
  x = tf.placeholder("float", [50,1])
  y = tf.placeholder("float", [50])

#name scope for hidden_layer
with tf.name_scope("hidden_layer"):
#creating variables for hidden layer
  W_h = tf.Variable(tf.random_normal([1,hidden_nodes]))    # 1 rows x n_hidden layers columns tensor with weight
  x_h = tf.nn.relu(tf.matmul(x, W_h))                      # 50 rows x n_hidden layers columns tensor with output of hidden layers,
                                                           #calculated by using relu function

#name scope for output
with tf.name_scope("output"):
#creating variables for output
  W_out = tf.Variable(tf.random_normal([hidden_nodes, 1]))  # n_hidden layers rows x 1 columns tensor with weight
  y_pred = tf.transpose(tf.matmul(x_h, W_out))              # predicted values for y 50 rows

#name scope for error   
with tf.name_scope("loss"):
#calculating squered error
  lvec = (y - y_pred)**2
#calculating sum of squered error
  l = tf.reduce_sum(lvec)

#name scope for optimalization  
with tf.name_scope("optimalization"):
#Minimizing sum of squered error by using AdamOptimizer
  train_op = tf.train.AdamOptimizer(.001).minimize(l)

#Training model
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for i in range(1000):
        loss, _ = sess.run([l, train_op], feed_dict={x: x_np, y: y_np})
        print("epoch: ", i+1, "sum of squered error: ", loss)

epoch:  1 sum of squered error:  931.30566
epoch:  2 sum of squered error:  920.41974
epoch:  3 sum of squered error:  909.60333
epoch:  4 sum of squered error:  898.8575
epoch:  5 sum of squered error:  888.1832
epoch:  6 sum of squered error:  877.5818
epoch:  7 sum of squered error:  867.05414
epoch:  8 sum of squered error:  856.6014
epoch:  9 sum of squered error:  846.22455
epoch:  10 sum of squered error:  835.9244
epoch:  11 sum of squered error:  825.702
epoch:  12 sum of squered error:  815.55835
epoch:  13 sum of squered error:  805.4941
epoch:  14 sum of squered error:  795.50995
epoch:  15 sum of squered error:  785.6066
epoch:  16 sum of squered error:  775.7851
epoch:  17 sum of squered error:  766.0457
epoch:  18 sum of squered error:  756.3893
epoch:  19 sum of squered error:  746.81604
epoch:  20 sum of squered error:  737.32666
epoch:  21 sum of squered error:  727.9214
epoch:  22 sum of squered error:  718.60095
epoch:  23 sum of squered error:  709.3655
epoch:  24 

epoch:  247 sum of squered error:  48.40919
epoch:  248 sum of squered error:  48.238247
epoch:  249 sum of squered error:  48.071762
epoch:  250 sum of squered error:  47.90964
epoch:  251 sum of squered error:  47.75178
epoch:  252 sum of squered error:  47.59809
epoch:  253 sum of squered error:  47.448467
epoch:  254 sum of squered error:  47.302807
epoch:  255 sum of squered error:  47.16104
epoch:  256 sum of squered error:  47.02305
epoch:  257 sum of squered error:  46.888775
epoch:  258 sum of squered error:  46.758106
epoch:  259 sum of squered error:  46.630962
epoch:  260 sum of squered error:  46.507267
epoch:  261 sum of squered error:  46.386932
epoch:  262 sum of squered error:  46.269875
epoch:  263 sum of squered error:  46.15602
epoch:  264 sum of squered error:  46.04529
epoch:  265 sum of squered error:  45.937607
epoch:  266 sum of squered error:  45.8329
epoch:  267 sum of squered error:  45.7311
epoch:  268 sum of squered error:  45.63212
epoch:  269 sum of sque

epoch:  459 sum of squered error:  42.48656
epoch:  460 sum of squered error:  42.486477
epoch:  461 sum of squered error:  42.4864
epoch:  462 sum of squered error:  42.48632
epoch:  463 sum of squered error:  42.48625
epoch:  464 sum of squered error:  42.486183
epoch:  465 sum of squered error:  42.48612
epoch:  466 sum of squered error:  42.48605
epoch:  467 sum of squered error:  42.486
epoch:  468 sum of squered error:  42.48594
epoch:  469 sum of squered error:  42.485878
epoch:  470 sum of squered error:  42.48583
epoch:  471 sum of squered error:  42.48578
epoch:  472 sum of squered error:  42.48573
epoch:  473 sum of squered error:  42.48569
epoch:  474 sum of squered error:  42.485645
epoch:  475 sum of squered error:  42.485596
epoch:  476 sum of squered error:  42.48556
epoch:  477 sum of squered error:  42.485523
epoch:  478 sum of squered error:  42.48548
epoch:  479 sum of squered error:  42.48545
epoch:  480 sum of squered error:  42.485416
epoch:  481 sum of squered e

epoch:  691 sum of squered error:  42.484768
epoch:  692 sum of squered error:  42.484768
epoch:  693 sum of squered error:  42.48477
epoch:  694 sum of squered error:  42.484768
epoch:  695 sum of squered error:  42.484764
epoch:  696 sum of squered error:  42.484764
epoch:  697 sum of squered error:  42.48476
epoch:  698 sum of squered error:  42.48477
epoch:  699 sum of squered error:  42.48477
epoch:  700 sum of squered error:  42.48477
epoch:  701 sum of squered error:  42.484764
epoch:  702 sum of squered error:  42.484768
epoch:  703 sum of squered error:  42.484768
epoch:  704 sum of squered error:  42.484768
epoch:  705 sum of squered error:  42.484768
epoch:  706 sum of squered error:  42.484764
epoch:  707 sum of squered error:  42.484768
epoch:  708 sum of squered error:  42.484768
epoch:  709 sum of squered error:  42.484764
epoch:  710 sum of squered error:  42.484768
epoch:  711 sum of squered error:  42.484764
epoch:  712 sum of squered error:  42.484764
epoch:  713 sum

epoch:  900 sum of squered error:  42.484768
epoch:  901 sum of squered error:  42.484768
epoch:  902 sum of squered error:  42.484768
epoch:  903 sum of squered error:  42.484768
epoch:  904 sum of squered error:  42.484768
epoch:  905 sum of squered error:  42.48477
epoch:  906 sum of squered error:  42.484768
epoch:  907 sum of squered error:  42.484768
epoch:  908 sum of squered error:  42.484768
epoch:  909 sum of squered error:  42.484768
epoch:  910 sum of squered error:  42.484768
epoch:  911 sum of squered error:  42.484768
epoch:  912 sum of squered error:  42.484768
epoch:  913 sum of squered error:  42.484768
epoch:  914 sum of squered error:  42.484768
epoch:  915 sum of squered error:  42.484768
epoch:  916 sum of squered error:  42.484768
epoch:  917 sum of squered error:  42.484768
epoch:  918 sum of squered error:  42.484768
epoch:  919 sum of squered error:  42.484768
epoch:  920 sum of squered error:  42.484768
epoch:  921 sum of squered error:  42.484768
epoch:  922